[Elasticsearch]
Endpoint                = "http://elasticsearch:9200"
ReviewsIndexName        = "ratings"
ReviewsTypeName         = "rating"
RestaurantsIndexName    = "restaurants"
RestaurantsTypeName     = "restaurant"