version: '3'
services:
  app:
    build: .
    command: ["sh", "wait-for-it.sh"]
    working_dir: /go/src/RestaurantSearcherAPI
    volumes:
      - .:/go/src/RestaurantSearcherAPI
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - redis
    environment:
        - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://elasticsearch:9200/_cat/health?h=st) = 200 ]
        - WAIT_START_CMD=go run main.go
        - WAIT_SLEEP=2
        - WAIT_LOOPS=100
  elasticsearch:
    image: elasticsearch:5.3.0
    command: elasticsearch
    volumes:
      - esdata:/var/lib/elastic
    ports:
      - "9200:9200"
  kibana:
    image: kibana:5.3.0
    command: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  redis:
    image: redis:latest
    volumes:
      - redisdata:/data

volumes:
  esdata:
    driver: local
  redisdata:
    driver: local
