version: '3'
services:
  app:
    build: .
    command: ["./wait-for-it.sh", "elastic:9200", "-t", "30", "--", "go", "run", "main.go"]
    volumes:
      - .:/go/src/RestaurantSearcherAPI
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch
    command: elasticsearch
    ports:
      - "9200:9200"